= Guidelines for Implementation of the Common Patent Policy for ITU-T/ITU-R/ISO/IEC
:title-main-en: Guidelines for Implementation of the Common Patent Policy for ITU-T/ITU-R/ISO/IEC
:docnumber: 99999
:copyright-year: 2018
:ref-docnumber: 99999:2018
:language: en
:docstage: 60
:docsubstage: 60
:edition: 4
:status: published
:revdate: 2018-11-02
:script: Latn
:technical-committee-type: IEC/ITU
:technical-committee: PUBLISH
:local-cache-only:
:data-uri-image:
:toc:

.Summary

The Guidelines for Implementation of the Common Patent Policy for ITU-T/ITU-R/ISO/IEC are intended to clarify and facilitate implementation of the Patent Policy, a copy of which can be found in Annex 1 and also on the web site of each Organization.

The Patent Policy encourages the early disclosure and identification of Patents that may relate to Recommendations | Deliverables under development. In doing so, greater efficiency in standards development is possible and potential patent rights problems can be avoided.

.History

Edition

* 1.0 Published initial version 1 March 2007
* 2.0 Published first revision 23 April 2012
* 3.0 Published second revision 26 June 2015
* 4.0 Published third revision 2 November 2018


== Part I – Common guidelines

=== Purpose

ITU, in its Telecommunication Standardization Sector (ITU-T) and its Radiocommunication Sector (ITU-R), ISO and IEC have had patent policies for many years, the purpose being to provide in simple words practical guidance to the participants in their Technical Bodies in case patent rights matters arise.

Considering that the technical experts are normally not familiar with the complex issue of patent law, the Common Patent Policy for ITU-T/ITU-R/ISO/IEC (hereafter referred to as the "Patent Policy") was drafted in its operative part as a checklist, covering the three different cases which may arise if a Recommendation | Deliverable requires licences for Patents to be practiced or implemented, fully or partly.

The Guidelines for Implementation of the Common Patent Policy for ITU-T/ITU-R/ISO/IEC (hereafter referred to as the "Guidelines") are intended to clarify and facilitate implementation of the Patent Policy, a copy of which can be found in Annex 1 and also on the web site of each Organization.

The Patent Policy encourages the early disclosure and identification of Patents that may relate to Recommendations | Deliverables under development. In doing so, greater efficiency in standards development is possible and potential patent rights problems can be avoided.

The Organizations should not be involved in evaluating patent relevance or essentiality with regards to Recommendations | Deliverables, interfere with licensing negotiations, or engage in settling disputes on Patents; this should be left - as in the past - to the parties concerned.

Organization-specific provisions are contained in Part II of this document. However, it is understood that those Organization-specific provisions shall contradict neither the Patent Policy nor the Guidelines.

=== Explanation of terms

Contribution:: Any document submitted for consideration by a Technical Body.

Free of Charge:: The words "Free of Charge" do not mean that the Patent Holder is waiving all of its rights with respect to the Patent. Rather, "Free of Charge" refers to the issue of monetary compensation; i.e., that the Patent Holder will not seek any monetary compensation as part of the licensing arrangement (whether such compensation is called a royalty, a one-time licensing fee, etc.). However, while the Patent Holder in this situation is committing to not charging any monetary amount, the Patent Holder is still entitled to require that the implementer of the relevant Recommendation | Deliverable sign a license agreement that contains other reasonable terms and conditions such as those relating to governing law, field of use, warranties, etc.

Organizations:: ITU, ISO and IEC.

Patent:: The word "Patent" means those claims contained in and identified by patents, utility models and other similar statutory rights based on inventions (including applications for any of these) solely to the extent that any such claims are essential to the implementation of a Recommendation | Deliverable. Essential patents are patents that would be required to implement a specific Recommendation | Deliverable.

Patent Holder:: Person or entity that owns, controls and/or has the ability to license Patents.

Reciprocity:: The word "Reciprocity" means that the Patent Holder shall only be required to license any prospective licensee if such prospective licensee will commit to license its Patent(s) for implementation of the same relevant Recommendation | Deliverable Free of Charge or under reasonable terms and conditions.

Recommendations | Deliverables:: ITU-T and ITU-R Recommendations are referred to as "Recommendations", ISO deliverables and IEC deliverables are referred to as "Deliverables". The various types of Recommendation(s) | Deliverable(s) are referred to as "Document types" in the Patent Statement and Licensing Declaration Form (hereafter referred to as "Declaration Form") attached as Annex 2.

Technical Bodies:: Study Groups, any subordinate groups and other groups of ITU-T and ITU-R and technical committees, subcommittees and working groups in ISO and IEC.

=== Patent disclosure

As mandated by the Patent Policy in its paragraph 1, any party participating footnote:[In the case of ISO and IEC, this includes any recipient of a draft standard at any stage in the standards development process.] in the work of the Organizations should, from the outset, draw their attention to any known Patent or to any known pending Patent application, either its own or that of other organizations.

In this context, the words "from the outset" imply that such information should be disclosed as early as possible during the development of the Recommendation | Deliverable. This might not be possible when the first draft text appears since at this time, the text might be still too vague or subject to subsequent major modifications. Moreover, that information should be provided in good faith and on a best effort basis, but there is no requirement for patent searches.

In addition to the above, any party not participating in Technical Bodies may draw the attention of the Organizations to any known Patent, either their own and/or of any third-party.

When disclosing their own Patents, Patent Holders have to use the Patent Statement and Licensing Declaration Form (referred to as the "Declaration Form") as stated in Section 4 of these Guidelines.


Any communication drawing the attention to any third-party Patent should be addressed to the concerned Organization(s) in writing. The potential Patent Holder will then be requested by the Director/CEO of the relevant Organization(s) to submit a Declaration Form, if applicable.

The Patent Policy and these Guidelines also apply to any Patent disclosed or drawn to the attention of the Organizations subsequent to the approval of a Recommendation | Deliverable.

Whether the identification of the Patent took place before or after the approval of the Recommendation | Deliverable, if the Patent Holder is unwilling to license under paragraph 2.1 or 2.2 of the Patent Policy, the Organizations will promptly advise the Technical Bodies responsible for the affected Recommendation | Deliverable so that appropriate action can be taken. Such action will include, but may not be limited to, a review of the Recommendation | Deliverable or its draft in order to remove the potential conflict or to further examine and clarify the technical considerations causing the conflict.

=== Patent Statement and Licensing Declaration Form

==== The purpose of the Declaration Form

To provide clear information in the Patent Information databases of each Organization, Patent Holders have to use the Declaration Form, which is available on the web site of each Organization (the Declaration Form is included in Annex 2 for information purposes). They must be sent to the Organizations for the attention, for ITU, of the Directors of the TSB or the BR or, for ISO or IEC, of the CEOs. The purpose of the Declaration Form is to ensure a standardized submission to the respective Organizations of the declarations being made by Patent Holders.

The Declaration Form gives Patent Holders the means of making a licensing declaration relative to rights in Patents required for implementation of a specific Recommendation | Deliverable. Specifically, by submitting this Declaration Form the submitting party declares its willingness to license (by selecting option 1 or 2 on the Form) /or its unwillingness to license (by selecting option 3 on the Form), according to the Patent Policy, Patents held by it and whose licence would be required to practice or implement part(s) or all of a specific Recommendation | Deliverable.

If a Patent Holder has selected the licensing option 3 on the Declaration Form, then, for the referenced relevant ITU Recommendation and ISO or IEC Deliverable, the ITU, ISO and IEC require the Patent Holder to provide certain additional information permitting patent identification.

Multiple Declaration Forms are appropriate if the Patent Holder wishes to identify several Patents and classifies them in different options of the Declaration Form for the same Recommendation | Deliverable or if the Patent Holder classifies different claims of a complex patent in different options of the Declaration Form.

Information contained in a Declaration Form may be corrected in case of obvious errors, such as a typographical mistake in a standard or patent reference number. The licensing declaration contained in the Declaration Form remains in force unless it is superseded by another Declaration Form containing more favourable licensing terms and conditions from a licensee's perspective reflecting (a) a change in commitment from option 3 to either option 1 or option 2, (b) a change in commitment from option 2 to option 1 or (c) un-checking one or more sub-options contained within option 1 or 2.

==== Contact information

In completing Declaration Forms, attention should be given to supplying contact information that will remain valid over time. Where possible, the "Name and Department" and e-mail address should be generic. Also it is preferable, where possible, that parties, particularly multinational organizations, indicate the same contact point on all Declaration Forms submitted.

With a view to maintaining up-to-date information in the Patent Information database of each Organization, it is requested that the Organizations be informed of any change or corrections to the Declaration Form submitted in the past, especially with regard to the contact person.

=== Conduct of meetings

Early disclosure of Patents contributes to the efficiency of the process by which Recommendations | Deliverables are established. Therefore, each Technical Body, in the course of the development of a proposed Recommendation | Deliverable, will request the disclosure of any known Patents essential to the proposed Recommendation | Deliverable.

Chairmen of Technical Bodies will, if appropriate, ask, at an appropriate time in each meeting, whether anyone has knowledge of patents, the use of which may be required to practice or implement the Recommendation | Deliverable being considered. The fact that the question was asked shall be recorded in the meeting report, along with any affirmative responses.

As long as the Organization concerned has received no indication of a Patent Holder selecting paragraph 2.3 of the Patent Policy, the Recommendation | Deliverable may be approved using the appropriate and respective rules of the Organization concerned. It is expected that discussions in Technical Bodies will include consideration of including patented material in a Recommendation | Deliverable, however the Technical Bodies may not take position regarding the essentiality, scope, validity or specific licensing terms of any claimed Patents.

=== Patent Information database

In order to facilitate both the standards-making process and the application of Recommendations | Deliverables, each Organization makes available to the public a Patent Information database composed of information that was communicated to the Organizations by the means of Declaration Forms. The Patent Information database may contain information on specific patents, or may contain no such information but rather a statement about compliance with the Patent Policy for a particular Recommendation | Deliverable.

The Patent Information databases are not certified to be either accurate or complete, but only reflect the information that has been communicated to the Organizations. As such, the Patent Information databases may be viewed as simply raising a flag to alert users that they may wish to contact the entities who have communicated Declaration Forms to the Organizations in order to determine if patent licenses must be obtained for use or implementation of a particular Recommendation | Deliverable.

=== Assignment or Transfer of Patent Rights

The rules governing the assignment or transfer of Patent rights are contained in the patent statement and licensing declaration forms (see Annexes 2 and 3). By complying with these rules, the Patent Holder has discharged in full all of its obligations and liability with regards to the licensing commitments after the transfer or assignment. These rules are not intended to place any duty on the Patent Holder to compel compliance with the licensing commitment by the assignee or transferee after the transfer occurs.


== Part II – Organization-specific provisions

=== Specific provisions for ITU

==== ITU-1 General Patent Statement and Licensing Declaration Form

Anyone may submit a General Patent Statement and Licensing Declaration Form which is available on the web sites of ITU-T and ITU-R (the form in Annex 3 is included for information purposes). The purpose of this form is to give Patent Holders the voluntary option of making a general licensing declaration relative to material protected by Patents contained in any of their Contributions. Specifically, by submitting its form, the Patent Holder declares its willingness to license its Patents owned by it in case part(s) or all of any proposals contained in its Contributions submitted to the Organization are included in Recommendation(s) and the included part(s) contain items for which Patents have been filed and whose licence would be required to practice or implement Recommendation(s).

The General Patent Statement and Licensing Declaration Form is not a replacement for the "individual" (see clause 4 of Part I) Declaration Form, which is made per Recommendation, but is expected to improve responsiveness and early disclosure of the Patent Holder's compliance with the Patent Policy. Therefore, in addition to its existing General Patent Statement and Licensing Declaration in respect of its Contributions, the Patent Holder should, when appropriate (e.g. if it becomes aware that it has a Patent for a specific Recommendation), also submit an "individual" Patent Statement and Licensing Declaration Form: +
--
* for the Patents contained in any of its Contributions submitted to the Organization which are included in a Recommendation, any such "individual" Patent Statement and Licensing Declarations may contain either the same licensing terms and conditions as in the General Patent Statement and Licensing Declaration Form, or more favourable licensing terms and conditions from a licensee's perspective as defined in the "individual" (see clause 4.1 of Part I) Declaration Form; and

* for the Patents that the Patent Holder did not contribute to the Organization which are included in a Recommendation, any such "individual" Patent Statement and Licensing Declarations may contain any of the three options available on the Form (see clause 4.1 of Part I), regardless of the commitment in its existing General Patent Statement and Licensing Declaration.
--

The General Patent Statement and Licensing Declaration remains in force unless it is superseded by another General Patent Statement and Licensing Declaration form containing more favourable licensing terms and conditions from a licensee's perspective reflecting (a) a change in commitment from option 2 to option 1 or (b) un-checking one or more sub- options contained within option 1 or 2.

The ITU Patent Information database also contains a record of General Patent Statement and Licensing Declarations.


==== ITU-2 Notification

Text shall be added to the cover sheets of all new and revised ITU-T and ITU-R Recommendations, where appropriate, urging users to consult the ITU Patent Information database. The wording is:

____
"ITU draws attention to the possibility that the practice or implementation of this Recommendation may involve the use of a claimed Intellectual Property Right. ITU takes no position concerning the evidence, validity or applicability of claimed Intellectual Property Rights, whether asserted by ITU members or others outside of the Recommendation development process.

As of the date of approval of this Recommendation, ITU [had/had not] received notice of intellectual property, protected by patents, which may be required to implement this Recommendation. However, implementers are cautioned that this may not represent the latest information and are therefore strongly urged to consult the ITU Patent Information database."
____


=== Specific provisions for ISO and IEC

==== ISO/IEC-1 Consultations on draft Deliverables

All drafts submitted for comment shall include on the cover page the following text:

____
"Recipients of this draft are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation."
____

==== ISO/IEC-2 Notification

A published document for which no patent rights are identified during the preparation thereof shall contain the following notice in the foreword:

____
"Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO [and/or] IEC shall not be held responsible for identifying any or all such patent rights."
____

A published document for which patent rights have been identified during the preparation thereof shall include the following notice in the introduction:

____
"The International Organization for Standardization (ISO) [and/or] International Electrotechnical Commission (IEC) draws attention to the fact that it is claimed that compliance with this document may involve the use of a patent concerning (... subject matter ...) given in (... subclause ...).

ISO [and/or] IEC take[s] no position concerning the evidence, validity and scope of this patent right.

The holder of this patent right has assured the ISO [and/or] IEC that he/she is willing to negotiate licences under reasonable and non-discriminatory terms and conditions with applicants throughout the world. In this respect, the statement of the holder of this patent right is registered with ISO [and/or] IEC. Information may be obtained from:

name of holder of patent right ...

address ...

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights other than those identified above. ISO [and/or] IEC shall not be held responsible for identifying any or all such patent rights."
____

==== ISO/IEC-3 National Adoptions

Patent Declarations in ISO, IEC and ISO/IEC Deliverables apply only to the ISO and/or IEC documents indicated in the Declaration Forms. Declarations do not apply to documents that are altered (such as through national or regional adoption). However, implementations that conform to identical national and regional adoptions and the respective ISO and/or IEC Deliverables, may rely on Declarations submitted to ISO and/or IEC for such Deliverables.


[appendix,obligation="normative"]
== Common patent policy for ITU-T/ITU-R/ISO/IEC

The following is a "code of practice" regarding patents covering, in varying degrees, the subject matters of ITU-T Recommendations, ITU-R Recommendations, ISO deliverables and IEC deliverables (for the purpose of this document, ITU-T and ITU-R Recommendations are referred to as "Recommendations", ISO deliverables and IEC deliverables are referred to as "Deliverables"). The rules of the "code of practice" are simple and straightforward. Recommendations | Deliverables are drawn up by technical and not patent experts; thus, they may not necessarily be very familiar with the complex international legal situation of intellectual property rights such as patents, etc.

Recommendations | Deliverables are non-binding; their objective is to ensure compatibility of technologies and systems on a worldwide basis. To meet this objective, which is in the common interests of all those participating, it must be ensured that Recommendations | Deliverables, their applications, use, etc. are accessible to everybody.

It follows, therefore, that a patent embodied fully or partly in a Recommendation | Deliverable must be accessible to everybody without undue constraints. To meet this requirement in general is the sole objective of the code of practice. The detailed arrangements arising from patents (licensing, royalties, etc.) are left to the parties concerned, as these arrangements might differ from case to case.

This code of practice may be summarized as follows:

. The ITU Telecommunication Standardization Bureau (TSB), the ITU Radio-communication Bureau (BR) and the offices of the CEOs of ISO and IEC are not in a position to give authoritative or comprehensive information about evidence, validity or scope of patents or similar rights, but it is desirable that the fullest available information should be disclosed. Therefore, any party participating in the work of ITU, ISO or IEC should, from the outset, draw the attention of the Director of ITU-TSB, the Director of ITU-BR, or the offices of the CEOs of ISO or IEC, respectively, to any known patent or to any known pending patent application, either their own or of other organizations, although ITU, ISO or IEC are unable to verify the validity of any such information.

. If a Recommendation | Deliverable is developed and such information as referred to in paragraph 1 has been disclosed, three different situations may arise:

.. The patent holder is willing to negotiate licences free of charge with other parties on a non-discriminatory basis on reasonable terms and conditions. Such negotiations are left to the parties concerned and are performed outside ITU-T/ITU-R/ISO/IEC.

.. The patent holder is willing to negotiate licences with other parties on a non- discriminatory basis on reasonable terms and conditions. Such negotiations are left to the parties concerned and are performed outside ITU-T/ITU-R/ISO/IEC.

.. The patent holder is not willing to comply with the provisions of either paragraph 2.1 or paragraph 2.2; in such case, the Recommendation | Deliverable shall not include provisions depending on the patent.

. Whatever case applies (2.1, 2.2 or 2.3), the patent holder has to provide a written statement to be filed at ITU-TSB, ITU-BR or the offices of the CEOs of ISO or IEC, respectively, using the appropriate "Patent Statement and Licensing Declaration" Form. This statement must not include additional provisions, conditions, or any other exclusion clauses in excess of what is provided for each case in the corresponding boxes of the form.
10

[appendix,obligation="normative"]
== Patent Statement and Licensing Declaration Form for ITU-T or ITU-R Recommendation | ISO or IEC Deliverable

Patent Statement and Licensing Declaration for ITU-T or ITU-R Recommendation | ISO or IEC Deliverable

_This declaration does not represent an actual grant of a license_

Please return to the relevant organization(s) as instructed below per document type:

[cols="a,a,a,a"]
|===

|
Director

Telecommunication Standardization Bureau

International Telecommunication Union

Place des Nations

CH-1211 Geneva 20, Switzerland

Fax: +41 22 730 5853

Email: tsbdir@itu.int

|
Director

Radiocommunication Bureau

International Telecommunication Union

Place des Nations

CH-1211 Geneva 20, Switzerland

Fax: +41 22 730 5785

Email: brmail@itu.int


|

Secretary-General

International Organization for Standardization

8 Chemin de Blandonnet

CP 401

1214 Vernier, Geneva Switzerland

Fax: +41 22 733 3430

Email: patent.statements@iso.org


|
General Secretary

International Electrotechnical Commission

3 rue de Varembé

CH-1211 Geneva 20 Switzerland

Fax: +41 22 919 0300

Email: inmail@iec.ch


|===




=== Patent Holder

* Legal Name: pass:[__________________________]


=== Contact for license application

* Name & Department pass:[__________________________]
* Address pass:[__________________________]
* Tel. pass:[__________________________]
* Fax pass:[__________________________]
* E-mail pass:[__________________________]
* URL (optional) pass:[__________________________]


=== Document type

(please return the form to the relevant Organization)

* [ ] ITU-T Rec.
* [ ] ITU-R Rec.
* [ ] ISO Deliverable
* [ ] IEC Deliverable

* [ ] Common text or twin text (ITU-T Rec. | ISO/IEC Deliverable) (for common text or twin text,
please return the form to each of the three Organizations: ITU-T, ISO, IEC)

* [ ] ISO/IEC Deliverable
(for ISO/IEC Deliverables, please return the form to both ISO and IEC)


=== Common

* Number  pass:[__________________________]

* Title  pass:[__________________________]


=== Licensing declaration

The Patent Holder believes that it holds granted and/or pending applications for Patents, the use of which would be required to implement the above document and hereby declares, in accordance with the Common Patent Policy for ITU-T/ITU-R/ISO/IEC, that (check one box only):

[ ] 1. The Patent Holder is prepared to grant a Free of Charge license to an unrestricted number of applicants on a worldwide, non-discriminatory basis and under other reasonable terms and conditions to make, use, and sell implementations of the above document.

Negotiations are left to the parties concerned and are performed outside the ITU-T, ITU-R, ISO or IEC.

Also mark here __ if the Patent Holder's willingness to license is conditioned on Reciprocity for the above document.

Also mark here __ if the Patent Holder reserves the right to license on reasonable terms and conditions (but not Free of Charge) to applicants who are only willing to license their Patent, whose use would be required to implement the above document, on reasonable terms and conditions (but not Free of Charge).

[ ] 2. The Patent Holder is prepared to grant a license to an unrestricted number of applicants on a worldwide, non-discriminatory basis and on reasonable terms and conditions to make, use and sell implementations of the above document.

Negotiations are left to the parties concerned and are performed outside the ITU-T, ITU-R, ISO, or IEC.

Also mark here __ if the Patent Holder's willingness to license is conditioned on Reciprocity for the above document.


[ ] 3. The Patent Holder is unwilling to grant licenses in accordance with provisions of either 1 or 2 above.

In this case, the following information must be provided to ITU, ISO and/or IEC as part of this declaration:

- granted patent number or patent application number (if pending);
- an indication of which portions of the above document are affected;
- a description of the Patents covering the above document.


Free of Charge:: The words "Free of Charge" do not mean that the Patent Holder is waiving all of its rights with respect to the Patent. Rather, "Free of Charge" refers to the issue of monetary compensation; i.e., that the Patent Holder will not seek any monetary compensation as part of the licensing arrangement (whether such compensation is called a royalty, a one-time licensing fee, etc.). However, while the Patent Holder in this situation is committing to not charging any monetary amount, the Patent Holder is still entitled to require that the implementer of the same above document sign a license agreement that contains other reasonable terms and conditions such as those relating to governing law, field of use, warranties, etc.

Reciprocity:: The word "Reciprocity" means that the Patent Holder shall only be required to license any prospective licensee if such prospective licensee will commit to license its Patent(s) for implementation of the same above document Free of Charge or under reasonable terms and conditions.

Patent:: The word "Patent" means those claims contained in and identified by patents, utility models and other similar statutory rights based on inventions (including applications for any of these) solely to the extent that any such claims are essential to the implementation of the same above document. Essential patents are patents that would be required to implement a specific Recommendation | Deliverable.

Assignment/transfer of Patent rights:: Licensing declarations made pursuant to Clause 2.1 or 2.2 of the Common Patent Policy for ITU-T/ITU-R/ISO/IEC shall be interpreted as encumbrances that bind all successors-in-interest as to the transferred Patents. Recognizing that this interpretation may not apply in all jurisdictions, any Patent Holder who has submitted a licensing declaration according to the Common Patent Policy - be it selected as option 1 or 2 on the Patent Declaration form - who transfers ownership of a Patent that is subject to such licensing declaration shall include appropriate provisions in the relevant transfer documents to ensure that, as to such transferred Patent, the licensing declaration is binding on the transferee and that the transferee will similarly include appropriate provisions in the event of future transfers with the goal of binding all successors-in-interest.

=== Patent Information

(desired but not required for options 1 and 2; required in ITU, ISO and IEC for option 3 (NOTE))

[cols="1,1,1,1,1",options="header"]
|===
|No.
|Status [granted/ pending]
|Country
|Granted Patent Number or Application Number (if pending)
|Title

|1||||
|2||||
|3||||
|4||||
|5||||
|6||||
|7||||
|8||||
|9||||
|10||||

|===

[ ] Check here if additional patent information is provided on additional pages.

NOTE: For option 3, the additional minimum information that shall also be provided is listed in the option 3 box above.

=== Signature (include on final page only)

* Patent Holder pass:[__________________________]
* Name of authorized person pass:[__________________________]
* Title of authorized person pass:[__________________________]
* Signature, Place, Date pass:[__________________________]


FORM: 2 November 2018

[appendix,obligation="normative"]
== General Patent Statement and Licensing Declaration Form for ITU-T or ITU-R Recommendation

_This declaration does not represent an actual grant of a license_

Please return to the relevant bureau:


[cols="a,a"]
|===

|
Director

Telecommunication Standardization Bureau

International Telecommunication Union

Place des Nations

CH-1211 Geneva 20, Switzerland

Fax: +41 22 730 5853

Email: tsbdir@itu.int

|
Director

Radiocommunication Bureau

International Telecommunication Union

Place des Nations

CH-1211 Geneva 20, Switzerland

Fax: +41 22 730 5785

Email: brmail@itu.int

|===



=== Patent Holder

* Legal Name pass:[__________________________]


=== Contact for license application

* Name & Department pass:[__________________________]
* Address pass:[__________________________]
* Tel. pass:[__________________________]
* Fax pass:[__________________________]
* E-mail pass:[__________________________]
* URL (optional) pass:[__________________________]


=== Licensing declaration

In case part(s) or all of any proposals contained in Contributions submitted by the Patent Holder above are included in ITU-T/ITU-R Recommendation(s) and the included part(s) contain items for which Patents have been filed and whose use would be required to implement ITU-T/ITU-R Recommendation(s), the above Patent Holder hereby declares, in accordance with the Common Patent Policy for ITU-T/ITU-R/ISO/IEC (check one box only):


[ ] 1. The Patent Holder is prepared to grant a Free of Charge license to an unrestricted number of applicants on a worldwide, non-discriminatory basis and under other reasonable terms and conditions to make, use, and sell implementations of the relevant ITU-T/ITU-R Recommendation.

Negotiations are left to the parties concerned and are performed outside the ITU-T/ITU-R.

Also mark here __ if the Patent Holder's willingness to license is conditioned on Reciprocity for the above ITU-T/ITU-R Recommendation.

Also mark here __ if the Patent Holder reserves the right to license on reasonable terms and conditions (but not Free of Charge) to applicants who are only willing to license their patent claims, whose use would be required to implement the above ITU-T/ITU-R Recommendation, on reasonable terms and conditions (but not Free of Charge).


[ ] 2. The Patent Holder is prepared to grant a license to an unrestricted number of applicants on a worldwide, non-discriminatory basis and on reasonable terms and conditions to make, use and sell implementations of the relevant ITU-T/ITU-R Recommendation.

Negotiations are left to the parties concerned and are performed outside the ITU-T/ITU-R.

Also mark here __ if the Patent Holder's willingness to license is conditioned on Reciprocity for the above ITU-T/ITU-R Recommendation.


Free of Charge:: The words "Free of Charge" do not mean that the Patent Holder is waiving all of its rights with respect to the Patent. Rather, "Free of Charge" refers to the issue of monetary compensation; i.e., that the Patent Holder will not seek any monetary compensation as part of the licensing arrangement (whether such compensation is called a royalty, a one-time licensing fee, etc.). However, while the Patent Holder in this situation is committing to not charging any monetary amount, the Patent Holder is still entitled to require that the implementer of the relevant ITU-T/ITU-R Recommendation sign a license agreement that contains other reasonable terms and conditions such as those relating to governing law, field of use, warranties, etc.


Reciprocity:: The word "Reciprocity" means that the Patent Holder shall only be required to license any prospective licensee if such prospective licensee will commit to license its Patent(s) for implementation of the relevant ITU-T/ITU-R Recommendation Free of Charge or under reasonable terms and conditions.

Patent:: The word "Patent" means those claims contained in and identified by patents, utility models and other similar statutory rights based on inventions (including applications for any of these) solely to the extent that any such claims are essential to the implementation of the relevant Recommendation | Deliverable. Essential patents are patents that would be required to implement a specific Recommendation | Deliverable.

Assignment/transfer of Patent rights:: Licensing declarations made pursuant to Clause 2.1 or 2.2 of the Common Patent Policy for ITU-T/ITU-R/ISO/IEC shall be interpreted as encumbrances that bind all successors-in-interest as to the transferred Patents. Recognizing that this interpretation may not apply in all jurisdictions, any Patent Holder who has submitted a licensing declaration according to the Common Patent Policy - be it selected as option 1 or 2 on the Patent Declaration form - who transfers ownership of a Patent that is subject to such licensing declaration shall include appropriate provisions in the relevant transfer documents to ensure that, as to such transferred Patent, the licensing declaration is binding on the transferee and that the transferee will similarly include appropriate provisions in the event of future transfers with the goal of binding all successors-in-interest.


=== Signature

* Patent Holder pass:[__________________________]
* Name of authorized person pass:[__________________________]
* Title of authorized person pass:[__________________________]
* Signature, Place, Date pass:[__________________________]



Published in Switzerland

GENEVA, 2018

