:repo-name: csd-directive-ipr-guidelines

= CalConnect Directive: Guidelines for the implementation of the CalConnect patent policy

This work item belongs to TC PUBLISH.

image:https://travis-ci.com/CalConnect/csd-directive-ipr-guidelines.svg?branch=master["Build Status", link="https://travis-ci.com/calconnect/csd-directive-ipr-guidelines"]

This document is available in its rendered forms here:

* https://calconnect.github.io/csd-directive-ipr-guidelines/[CalConnect Directive: Guidelines for the implementation of the CalConnect patent policy (HTML)]
* https://calconnect.github.io/csd-directive-ipr-guidelines/csd-directive-ipr-guidelines.pdf[PDF]
* https://calconnect.github.io/csd-directive-ipr-guidelines/csd-directive-ipr-guidelines.xml[Metanorma XML]
* https://calconnect.github.io/csd-directive-ipr-guidelines/csd-directive-ipr-guidelines.rxl[Relaton XML (Bibliographic item)]


== Fetching the document

[source,sh]
----
git clone https://gitlab.com/calconnect/csd-directive-ipr-guidelines/
----

== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* CSD XML (https://github.com/calconnect/metanorma-model-csd) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open csd-*.html
----

