
[[patent-disclosure]]
== Patent disclosure


=== General

This clause describes the principles of patent disclosure
of patents that may affect CalConnect standardization deliverables produced
by CalConnect.

This clause applies to any patent disclosed or drawn
to the attention of CalConnect during the development
of and subsequent to the approval of deliverables.

=== Requirements

==== Participation obligation

All parties participating in the standardization activities of CalConnect
are obligated to inform CalConnect of
any known patent or to any known pending patent application,
as mandated by <<CC10003,clause=1>>

Where such parties include recipients of a draft CalConnect standardization deliverable at any stage,
and the patent or patent application could be of the party's own or
that of other entities.

==== Early disclosure

Patent information should be disclosed as early as possible during the development of the deliverable.

Such patent information should be provided in good faith and on a best effort basis. There is no requirement for patent searches.

NOTE: This might not be possible when the first draft text appears since at this time, the text might be still too vague or subject to subsequent major modifications.


==== External-originating disclosure

Parties not participating in the standardization activities of CalConnect may also inform CalConnect to any known patent, either their own and/or of any third-party, that may cover a CalConnect deliverable.


=== Method of disclosure

==== Declaration form

When disclosing their own patents, patent holders shall fill in the "`Patent Statement and Licensing Declaration Form`" (referred to as the "`declaration form`") as stated in <<patent-form>>.

==== Third-party patent disclosure

Any communication drawing the attention to any third-party patent
should be addressed to CalConnect in writing.

The Executive Director of CalConnect will then request the potential
patent holder to submit a declaration form, if applicable.


=== Resolution to discriminatory licensing

If a patent holder is unwilling to license under <<CC10003,clause=2.1>> or <<CC10003,clause=2.2>>, CalConnect will promptly advise the project owner(s) responsible for the affected deliverable so that appropriate action can be taken.

Such action shall include, but may not be limited to:

* a review of the CalConnect standardization deliverable or its draft in order to remove the potential conflict; or
* to further examine and clarify the technical considerations causing the conflict.

NOTE: This clause does not differentiate whether identification of the patent took place before or after the approval of the deliverable.
