
[[requirements]]
== Requirements on deliverables

=== Draft deliverables

All drafts submitted for comment shall include on the cover page the following text:

____
"Recipients of this draft are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation."
____

=== Notification

A published document for which no patent rights are identified during the preparation thereof shall contain the following notice in the foreword:

____
"Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO [and/or] IEC shall not be held responsible for identifying any or all such patent rights."
____

A published document for which patent rights have been identified during the preparation thereof shall include the following notice in the introduction:

____
"The International Organization for Standardization (ISO) [and/or] International Electrotechnical Commission (IEC) draws attention to the fact that it is claimed that compliance with this document may involve the use of a patent concerning (... subject matter ...) given in (... subclause ...).

ISO [and/or] IEC take[s] no position concerning the evidence, validity and scope of this patent right.

The holder of this patent right has assured the ISO [and/or] IEC that he/she is willing to negotiate licences under reasonable and non-discriminatory terms and conditions with applicants throughout the world. In this respect, the statement of the holder of this patent right is registered with ISO [and/or] IEC. Information may be obtained from:

name of holder of patent right ...

address ...

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights other than those identified above. ISO [and/or] IEC shall not be held responsible for identifying any or all such patent rights."
____

=== Collaborative developed deliverables

Patent Declarations in ISO, IEC and ISO/IEC Deliverables apply only to the ISO and/or IEC documents indicated in the Declaration Forms. Declarations do not apply to documents that are altered (such as through national or regional adoption). However, implementations that conform to identical national and regional adoptions and the respective ISO and/or IEC Deliverables, may rely on Declarations submitted to ISO and/or IEC for such Deliverables.
