
[appendix,obligation="normative"]
== Patent statement and licensing declaration for CalConnect deliverables

_This declaration does not represent an actual grant of a license_

Please submit this form to the following contact:

[cols="a,a"]
|===

|
Patent officer

The Calendaring and Scheduling Consortium, Inc.

4390 Chaffin Lane

McKinleyville

California 95519

United States of America

Email: patents@calconnect.org

|

|===



=== Patent Holder

* Legal Name: pass:[__________________________]


=== Contact for license application

* Name & Department pass:[__________________________]
* Address pass:[__________________________]
* Tel. pass:[__________________________]
* Fax pass:[__________________________]
* E-mail pass:[__________________________]
* URL (optional) pass:[__________________________]


=== Document type

(please return the form to the relevant Organization)

* [ ] CalConnect Deliverable

* [ ] CalConnect/ISO Deliverable
(for CalConnect/ISO Deliverables, please return the form to both CalConnect and ISO)


=== Common

* Number  pass:[__________________________]

* Title  pass:[__________________________]


=== Licensing declaration

The Patent Holder believes that it holds granted and/or pending applications for Patents, the use of which would be required to implement the above document and hereby declares, in accordance with the Common Patent Policy for ITU-T/ITU-R/ISO/IEC, that (check one box only):

[ ] 1. The Patent Holder is prepared to grant a Free of Charge license to an unrestricted number of applicants on a worldwide, non-discriminatory basis and under other reasonable terms and conditions to make, use, and sell implementations of the above document.

Negotiations are left to the parties concerned and are performed outside the ITU-T, ITU-R, ISO or IEC.

Also mark here __ if the Patent Holder's willingness to license is conditioned on Reciprocity for the above document.

Also mark here __ if the Patent Holder reserves the right to license on reasonable terms and conditions (but not Free of Charge) to applicants who are only willing to license their Patent, whose use would be required to implement the above document, on reasonable terms and conditions (but not Free of Charge).

[ ] 2. The Patent Holder is prepared to grant a license to an unrestricted number of applicants on a worldwide, non-discriminatory basis and on reasonable terms and conditions to make, use and sell implementations of the above document.

Negotiations are left to the parties concerned and are performed outside the ITU-T, ITU-R, ISO, or IEC.

Also mark here __ if the Patent Holder's willingness to license is conditioned on Reciprocity for the above document.


[ ] 3. The Patent Holder is unwilling to grant licenses in accordance with provisions of either 1 or 2 above.

In this case, the following information must be provided to ITU, ISO and/or IEC as part of this declaration:

- granted patent number or patent application number (if pending);
- an indication of which portions of the above document are affected;
- a description of the Patents covering the above document.

////
Free of Charge:: The words "Free of Charge" do not mean that the Patent Holder is waiving all of its rights with respect to the Patent. Rather, "Free of Charge" refers to the issue of monetary compensation; i.e., that the Patent Holder will not seek any monetary compensation as part of the licensing arrangement (whether such compensation is called a royalty, a one-time licensing fee, etc.). However, while the Patent Holder in this situation is committing to not charging any monetary amount, the Patent Holder is still entitled to require that the implementer of the same above document sign a license agreement that contains other reasonable terms and conditions such as those relating to governing law, field of use, warranties, etc.

Reciprocity:: The word "Reciprocity" means that the Patent Holder shall only be required to license any prospective licensee if such prospective licensee will commit to license its Patent(s) for implementation of the same above document Free of Charge or under reasonable terms and conditions.

Patent:: The word "Patent" means those claims contained in and identified by patents, utility models and other similar statutory rights based on inventions (including applications for any of these) solely to the extent that any such claims are essential to the implementation of the same above document. Essential patents are patents that would be required to implement a specific Recommendation | Deliverable.

Assignment/transfer of Patent rights:: Licensing declarations made pursuant to Clause 2.1 or 2.2 of the Common Patent Policy for ITU-T/ITU-R/ISO/IEC shall be interpreted as encumbrances that bind all successors-in-interest as to the transferred Patents. Recognizing that this interpretation may not apply in all jurisdictions, any Patent Holder who has submitted a licensing declaration according to the Common Patent Policy - be it selected as option 1 or 2 on the Patent Declaration form - who transfers ownership of a Patent that is subject to such licensing declaration shall include appropriate provisions in the relevant transfer documents to ensure that, as to such transferred Patent, the licensing declaration is binding on the transferee and that the transferee will similarly include appropriate provisions in the event of future transfers with the goal of binding all successors-in-interest.
////

=== Patent Information

(desired but not required for options 1 and 2; required in ITU, ISO and IEC for option 3 (NOTE))

[cols="1,1,1,1,1",options="header"]
|===
|No.
|Status [granted/ pending]
|Country
|Granted Patent Number or Application Number (if pending)
|Title

|1||||
|2||||
|3||||
|4||||
|5||||
|6||||
|7||||
|8||||
|9||||
|10||||

|===

[ ] Check here if additional patent information is provided on additional pages.

NOTE: For option 3, the additional minimum information that shall also be provided is listed in the option 3 box above.

=== Signature (include on final page only)

* Patent Holder pass:[__________________________]
* Name of authorized person pass:[__________________________]
* Title of authorized person pass:[__________________________]
* Signature, Place, Date pass:[__________________________]


